CREATE DATABASE IF NOT EXISTS SRP CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE SRP;

CREATE TABLE IF NOT EXISTS tareas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT NOT NULL,
    tipo VARCHAR(20) DEFAULT 'normal',
    fechaLimite DATE
);